### ISSUE TITLE
在network.py的61行有什么特别的用意吗？

### ISSUE THREAD

**Issue by zjysnow** [AndreGuo/ITMLUT#2]
如题
LUTs_d = self.lut_gen_b(weights_d)
这里为啥用lut_gen_b来生成LUTs_d？

**Comment by AndreGuo** [comment]
该行代码为笔误，我们马上修复该问题，修复完毕后将关闭该问题。
LUTs_d = self.lut_gen_b(weights_d)
It's a mistake, we will fix it soon, it should be:
LUTs_d = self.lut_gen_d(weights_d)
We will fix it soon, and will close this issue once fixed.

**Comment by AndreGuo** [comment]
该问题已于`network.py`以及训练代码中修复。剩余模型参数尚需对应精调，新模型参数上传完毕后将关闭该问题。
This mistake is now fixed in `network.py` and the training code. Still need to refine the model parameters accordingly, we'll close this issue once new parameters are uplaoded.
